# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Canihazgnomeupdate < Formula
  desc "check if all your extensions support a specific gnome version "
  homepage "https://jon4hz.io"
  version "0.1.1"
  depends_on :linux

  if Hardware::CPU.intel?
    url "https://github.com/jon4hz/canihazgnomeupdate/releases/download/v0.1.1/canihazgnomeupdate-v0.1.1-linux-amd64.tar.gz"
    sha256 "2b5796bb46a137558807c016c51d1f6654a3e76018b76b9e8850597f882f1652"

    def install
      bin.install "canihazgnomeupdate"
    end
  end
end
