# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fztea < Formula
  desc "TUI to interact with your flipper zero"
  homepage "https://jon4hz.io"
  version "0.6.4"

  on_macos do
    on_intel do
      url "https://github.com/jon4hz/fztea/releases/download/v0.6.4/fztea-v0.6.4-darwin-amd64.tar.gz"
      sha256 "28478b977e28735750cc95be2343184dc7eb8aee588b022e81bbd2fae96b5506"

      def install
        bin.install "fztea"
        bash_completion.install "completions/fztea.bash" => "fztea"
        zsh_completion.install "completions/fztea.zsh" => "_fztea"
        fish_completion.install "completions/fztea.fish"
        man1.install "manpages/fztea.1.gz"
      end
    end
    on_arm do
      url "https://github.com/jon4hz/fztea/releases/download/v0.6.4/fztea-v0.6.4-darwin-arm64.tar.gz"
      sha256 "ca9cc31d455d985e74f2c6583231ea4d07b3f36a4c70075d3e773073ba3c6219"

      def install
        bin.install "fztea"
        bash_completion.install "completions/fztea.bash" => "fztea"
        zsh_completion.install "completions/fztea.zsh" => "_fztea"
        fish_completion.install "completions/fztea.fish"
        man1.install "manpages/fztea.1.gz"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jon4hz/fztea/releases/download/v0.6.4/fztea-v0.6.4-linux-amd64.tar.gz"
        sha256 "4126647b50969f28eb06092ef02b214675c0081d6f069312a94c03e5ea7620fc"

        def install
          bin.install "fztea"
          bash_completion.install "completions/fztea.bash" => "fztea"
          zsh_completion.install "completions/fztea.zsh" => "_fztea"
          fish_completion.install "completions/fztea.fish"
          man1.install "manpages/fztea.1.gz"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jon4hz/fztea/releases/download/v0.6.4/fztea-v0.6.4-linux-arm64.tar.gz"
        sha256 "ebf274075f4aede432a97f2ce33f080d44e653a576e98c64e43092b00335dc9e"

        def install
          bin.install "fztea"
          bash_completion.install "completions/fztea.bash" => "fztea"
          zsh_completion.install "completions/fztea.zsh" => "_fztea"
          fish_completion.install "completions/fztea.fish"
          man1.install "manpages/fztea.1.gz"
        end
      end
    end
  end
end
