# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fztea < Formula
  desc "TUI to interact with your flipper zero"
  homepage "https://jon4hz.io"
  version "0.6.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jon4hz/fztea/releases/download/v0.6.2/fztea-v0.6.2-darwin-arm64.tar.gz"
      sha256 "939f625d248333c99b72733f65416342cab797768a04b8b7f75d3ebe15dbe6cb"

      def install
        bin.install "fztea"
        bash_completion.install "completions/fztea.bash" => "fztea"
        zsh_completion.install "completions/fztea.zsh" => "_fztea"
        fish_completion.install "completions/fztea.fish"
        man1.install "manpages/fztea.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jon4hz/fztea/releases/download/v0.6.2/fztea-v0.6.2-darwin-amd64.tar.gz"
      sha256 "230926e862d987120dadff8f9a11a38a83911457ecb13979993b672c78ee7b49"

      def install
        bin.install "fztea"
        bash_completion.install "completions/fztea.bash" => "fztea"
        zsh_completion.install "completions/fztea.zsh" => "_fztea"
        fish_completion.install "completions/fztea.fish"
        man1.install "manpages/fztea.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jon4hz/fztea/releases/download/v0.6.2/fztea-v0.6.2-linux-arm64.tar.gz"
      sha256 "06a4331bc9152628e3b79cddbf0e52fc6360990ed779dad5c6ea4757e01a4054"

      def install
        bin.install "fztea"
        bash_completion.install "completions/fztea.bash" => "fztea"
        zsh_completion.install "completions/fztea.zsh" => "_fztea"
        fish_completion.install "completions/fztea.fish"
        man1.install "manpages/fztea.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jon4hz/fztea/releases/download/v0.6.2/fztea-v0.6.2-linux-amd64.tar.gz"
      sha256 "f04c0598fbc6ff4abedc1ceb11723eb2d319be5806c517a52c77358615498a7f"

      def install
        bin.install "fztea"
        bash_completion.install "completions/fztea.bash" => "fztea"
        zsh_completion.install "completions/fztea.zsh" => "_fztea"
        fish_completion.install "completions/fztea.fish"
        man1.install "manpages/fztea.1.gz"
      end
    end
  end
end
