# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fztea < Formula
  desc "TUI to interact with your flipper zero"
  homepage "https://jon4hz.io"
  version "0.6.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/jon4hz/fztea/releases/download/v0.6.3/fztea-v0.6.3-darwin-arm64.tar.gz"
      sha256 "bf29e93fe66ba8c05181fdb2a0d043ccc700bf9d580c4e3115d26997a3bc6d30"

      def install
        bin.install "fztea"
        bash_completion.install "completions/fztea.bash" => "fztea"
        zsh_completion.install "completions/fztea.zsh" => "_fztea"
        fish_completion.install "completions/fztea.fish"
        man1.install "manpages/fztea.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jon4hz/fztea/releases/download/v0.6.3/fztea-v0.6.3-darwin-amd64.tar.gz"
      sha256 "54ed6ac6ea532533ab4d7f107cf127d4832851111985bba0bb9f48041dacf40b"

      def install
        bin.install "fztea"
        bash_completion.install "completions/fztea.bash" => "fztea"
        zsh_completion.install "completions/fztea.zsh" => "_fztea"
        fish_completion.install "completions/fztea.fish"
        man1.install "manpages/fztea.1.gz"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jon4hz/fztea/releases/download/v0.6.3/fztea-v0.6.3-linux-arm64.tar.gz"
      sha256 "1787c40dd952d6089156d8d282b2300efd5a15c274472ecb280eeea76b0c22c4"

      def install
        bin.install "fztea"
        bash_completion.install "completions/fztea.bash" => "fztea"
        zsh_completion.install "completions/fztea.zsh" => "_fztea"
        fish_completion.install "completions/fztea.fish"
        man1.install "manpages/fztea.1.gz"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/jon4hz/fztea/releases/download/v0.6.3/fztea-v0.6.3-linux-amd64.tar.gz"
      sha256 "d2655700bf75ac563c40ddf3e2f37f1df3a772ab7bac93bee34b40077c8a3b0b"

      def install
        bin.install "fztea"
        bash_completion.install "completions/fztea.bash" => "fztea"
        zsh_completion.install "completions/fztea.zsh" => "_fztea"
        fish_completion.install "completions/fztea.fish"
        man1.install "manpages/fztea.1.gz"
      end
    end
  end
end
