# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gmotd < Formula
  desc "a configurable, dynamic motd generator"
  homepage "https://jon4hz.io"
  version "0.2.0"
  depends_on :linux

  if Hardware::CPU.intel?
    url "https://github.com/jon4hz/gmotd/releases/download/v0.2.0/gmotd-v0.2.0-linux-amd64.tar.gz"
    sha256 "27543949fe14ac28491cdf5a496df87f69db57403aff3bb33ad56b60c732b903"

    def install
      bin.install "gmotd"
    end
  end
end
